version: '3'
services:
  scraping-microservice:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379
  nginx:
    image: nginx:1.23.4
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - scraping-microservice
  prometheus:
    image: prom/prometheus:v2.37
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:8.5.13
    ports:
      - 3000:3000
