---
global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  - job_name: scraping-microservice
    static_configs:
      - targets:
          - scraping-microservice:3000
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
#  route:
#    receiver: email
#    routes:
#      - match:
#          severity: critical
#        receiver: email
#      - match:
#          severity: warning
#        receiver: email
