name: Deployment

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '18.16.0'
      
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/scraper-microservice:${{ github.sha }} .
      
    - name: Log into Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/scraper-microservice:${{ github.sha }}

    - name: Apply version tag
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git tag -a "v${{ github.run_number }}" -m "version ${{ github.run_number }}"
        git push origin "v${{ github.run_number }}"
