name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.check_release.outputs.release }}

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.16.0'
      
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/scraper-microservice:${{ github.sha }} .
      
    - name: Log into Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/scraper-microservice:${{ github.sha }}
      
    - name: Check for release commit
      id: check_release
      run: echo "::set-output name=release::$(git log -1 --pretty=%B | grep -c 'Release version')"

  deploy:
    needs: build-and-test
    if: ${{ needs.build-and-test.outputs.release == '1' }}
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.16.0'
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test
    - name: Deploy to production
      run: git push origin main:production

